#!/usr/bin/python3


from math import gcd
from sys import argv

"""
this is the function to return the trivials of n
"""


def challenging(n):
    x = 2
    y = 2
    d = 1

    def f(x):

        return (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)
    if d != n:
        return d


def read_file():
    """
    the function to deal with the file reading
    """
    with open(argv[1]) as f:
        for n in f:
            num = int(n)
            if num % 2 == 0:
                print("{:d}={}*{}".format(num, num // 2, 2))
            else:
                p = challenging(num)
                factor1 = p
                factor2 = int(num / p)
                print("{}={}*{}".format(num, factor1, factor2))


if __name__ == "__main__":
    read_file()
